<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.3.1" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>99355293-c2df-4fda-a7ef-16f0422cf931</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UwiTestData.ApiService\UwiTestData.ApiService.csproj" />
    <ProjectReference Include="..\UwiTestData.Web\UwiTestData.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.1" />
  </ItemGroup>

</Project>
